version: "3.1"
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  api:
    build: .
    container_name: api
    restart: always
    env_file:
     - .env
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
    command: npm run start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
